
SET foreign_key_checks = 0;

DROP TABLE IF EXISTS `companies`;
DROP TABLE IF EXISTS `company_contact_person`;
DROP TABLE IF EXISTS `company_emails`;
DROP TABLE IF EXISTS `company_phonesnumbers`;
DROP TABLE IF EXISTS `company_postaladdresses`;
DROP TABLE IF EXISTS `company_status`;
DROP TABLE IF EXISTS `emails`;
DROP TABLE IF EXISTS `migration`;
DROP TABLE IF EXISTS `milestone`;
DROP TABLE IF EXISTS `milestone_task`;
DROP TABLE IF EXISTS `milestone_workflow`;
DROP TABLE IF EXISTS `project_access_type`;
DROP TABLE IF EXISTS `project_bfc_files`;
DROP TABLE IF EXISTS `project_comments`;
DROP TABLE IF EXISTS `project_comments_files`;
DROP TABLE IF EXISTS `project_ifc`;
DROP TABLE IF EXISTS `project_ifc_files`;
DROP TABLE IF EXISTS `project_other_files`;
DROP TABLE IF EXISTS `project_responsible`;
DROP TABLE IF EXISTS `project_roles`;
DROP TABLE IF EXISTS `project_status`;
DROP TABLE IF EXISTS `project_types`;
DROP TABLE IF EXISTS `project_users`;
DROP TABLE IF EXISTS `projects`;
DROP TABLE IF EXISTS `roles`;
DROP TABLE IF EXISTS `tasks`;
DROP TABLE IF EXISTS `team`;
DROP TABLE IF EXISTS `team_members`;
DROP TABLE IF EXISTS `toolbars`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `user_project_access`;
DROP TABLE IF EXISTS `user_project_roles`;
DROP TABLE IF EXISTS `user_roles`;
DROP TABLE IF EXISTS `user_status`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `workflow`;
DROP TABLE IF EXISTS `workflow_tasks`;
DROP TABLE IF EXISTS `workflow_type`;

SET foreign_key_checks = 1;